function changenews(obj){//16种情况未写全，如需写全以此类推补全即可
	if(obj==1)
	{
		document.getElementById("show1").style.display="block";
		document.getElementById("show2").style.display="none";
		document.getElementById("show3").style.display="none";
		document.getElementById("show4").style.display="none";
		document.getElementById("show5").style.display="none";
		document.getElementById("show6").style.display="none";
		document.getElementById("show7").style.display="none";
		document.getElementById("show8").style.display="none";
		document.getElementById("show9").style.display="none";
		document.getElementById("show10").style.display="none";
		document.getElementById("show11").style.display="none";
		document.getElementById("show12").style.display="none";
		document.getElementById("show13").style.display="none";
		document.getElementById("show14").style.display="none";
		document.getElementById("show15").style.display="none";
		document.getElementById("show15").style.display="none";
	}
	if(obj==2)
	{
		document.getElementById("show1").style.display="none";
		document.getElementById("show2").style.display="block";
		document.getElementById("show3").style.display="none";
		document.getElementById("show4").style.display="none";
		document.getElementById("show5").style.display="none";
		document.getElementById("show6").style.display="none";
		document.getElementById("show7").style.display="none";
		document.getElementById("show8").style.display="none";
		document.getElementById("show9").style.display="none";
		document.getElementById("show10").style.display="none";
		document.getElementById("show11").style.display="none";
		document.getElementById("show12").style.display="none";
		document.getElementById("show13").style.display="none";
		document.getElementById("show14").style.display="none";
		document.getElementById("show15").style.display="none";
		document.getElementById("show15").style.display="none";
	}
	if(obj==3)
	{
		document.getElementById("show1").style.display="none";
		document.getElementById("show2").style.display="none";
		document.getElementById("show3").style.display="block";
		document.getElementById("show4").style.display="none";
		document.getElementById("show5").style.display="none";
		document.getElementById("show6").style.display="none";
		document.getElementById("show7").style.display="none";
		document.getElementById("show8").style.display="none";
		document.getElementById("show9").style.display="none";
		document.getElementById("show10").style.display="none";
		document.getElementById("show11").style.display="none";
		document.getElementById("show12").style.display="none";
		document.getElementById("show13").style.display="none";
		document.getElementById("show14").style.display="none";
		document.getElementById("show15").style.display="none";
		document.getElementById("show15").style.display="none";
	}
	if(obj==4)
	{
		document.getElementById("show1").style.display="block";
		document.getElementById("show2").style.display="none";
		document.getElementById("show3").style.display="none";
		document.getElementById("show4").style.display="none";
		document.getElementById("show5").style.display="none";
		document.getElementById("show6").style.display="none";
		document.getElementById("show7").style.display="none";
		document.getElementById("show8").style.display="none";
		document.getElementById("show9").style.display="none";
		document.getElementById("show10").style.display="none";
		document.getElementById("show11").style.display="none";
		document.getElementById("show12").style.display="none";
		document.getElementById("show13").style.display="none";
		document.getElementById("show14").style.display="none";
		document.getElementById("show15").style.display="none";
		document.getElementById("show15").style.display="none";
	}
	
	if(obj==5)
	{
		document.getElementById("show1").style.display="block";
		document.getElementById("show2").style.display="none";
		document.getElementById("show3").style.display="none";
		document.getElementById("show4").style.display="none";
		document.getElementById("show5").style.display="none";
		document.getElementById("show6").style.display="none";
		document.getElementById("show7").style.display="none";
		document.getElementById("show8").style.display="none";
		document.getElementById("show9").style.display="none";
		document.getElementById("show10").style.display="none";
		document.getElementById("show11").style.display="none";
		document.getElementById("show12").style.display="none";
		document.getElementById("show13").style.display="none";
		document.getElementById("show14").style.display="none";
		document.getElementById("show15").style.display="none";
		document.getElementById("show15").style.display="none";
	}
	
} 